import Attention3D.Triangulation

/-!
# Ear triangulations cover the cone of a convex polygon

This file proves the covering statement behind `lem:frames` item 1 for one normal polygon, in its
cone form: every vector of the cone generated by the polygon's vertices lies in the cone of one
triangle of the alternating-ear triangulation, with unique and nonnegative coefficients.

The polygon is a list `c` of vectors of `ℝ³`. Its convex position in cyclic order is not derived
from the hull here. It enters as the hypothesis `CCW c` (every three entries, taken in list order,
have positive determinant) or `CW c` (every such determinant is negative). These hypotheses stand
in for two facts from `app:frames`: every incident facet normal of a hull vertex is a vertex of the
normal polygon, and the incident facets are listed in their cyclic order around the vertex. For
vectors in a plane `{u | u ⬝ᵥ w = 1}`, which does not contain zero, `det3 a b e` is positive
exactly when the triangle `a, b, e` runs counterclockwise within that plane, seen from the side to
which `w` points. Hence a list of vertices of a convex polygon in such a plane, in cyclic order and
with no vertex in the convex hull of the others, satisfies `CCW` or `CW`. These standard facts are
not formalized. The covering argument itself does not use the plane.

Main results:
* `IsEarSequence.cover`: the triangles of any ear sequence of a `CCW` list cover its cone.
* `exists_unique_coeffs_alternatingEars`: every vector of the cone has a unique representation
  with nonnegative coefficients in some triangle of the alternating-ear triangulation.
* `exists_unique_coeffs_alternatingEars_of_convex`: the same under `CCW c ∨ CW c`.
-/

namespace Attention3D

namespace Triangulation

/-! ### Determinants -/

/-- The determinant of the three vectors `a, b, c` of `ℝ³`, written out (the triple product). -/
def det3 (a b c : Fin 3 → ℝ) : ℝ :=
  a 0 * (b 1 * c 2 - b 2 * c 1) - a 1 * (b 0 * c 2 - b 2 * c 0) + a 2 * (b 0 * c 1 - b 1 * c 0)

/-- `det3` is the determinant of the matrix with rows `a, b, c`. -/
theorem det3_eq_det (a b c : Fin 3 → ℝ) : det3 a b c = (Matrix.of ![a, b, c]).det := by
  rw [Matrix.det_fin_three]
  simp only [det3, Matrix.of_apply, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.cons_val_two, Matrix.tail_cons, Matrix.head_cons]
  ring

theorem det3_cycle (a b c : Fin 3 → ℝ) : det3 a b c = det3 b c a := by
  unfold det3; ring

theorem det3_swap (a b c : Fin 3 → ℝ) : det3 b a c = -det3 a b c := by
  unfold det3; ring

theorem det3_self_left (a b : Fin 3 → ℝ) : det3 a b a = 0 := by
  unfold det3; ring

theorem det3_self_right (a b : Fin 3 → ℝ) : det3 a b b = 0 := by
  unfold det3; ring

theorem det3_add (a b u v : Fin 3 → ℝ) : det3 a b (u + v) = det3 a b u + det3 a b v := by
  simp only [det3, Pi.add_apply]; ring

theorem det3_smul (a b u : Fin 3 → ℝ) (t : ℝ) : det3 a b (t • u) = t * det3 a b u := by
  simp only [det3, Pi.smul_apply, smul_eq_mul]; ring

theorem det3_zero (a b : Fin 3 → ℝ) : det3 a b 0 = 0 := by
  simp only [det3, Pi.zero_apply]; ring

theorem det3_sum (a b : Fin 3 → ℝ) {ι : Type*} (S : Finset ι) (μ : ι → ℝ)
    (y : ι → Fin 3 → ℝ) : det3 a b (∑ i ∈ S, μ i • y i) = ∑ i ∈ S, μ i * det3 a b (y i) := by
  classical
  induction S using Finset.induction_on with
  | empty => simp [det3_zero]
  | insert i S hi ih => rw [Finset.sum_insert hi, Finset.sum_insert hi, det3_add, det3_smul, ih]

/-- Cramer's rule in the form of a vector identity. -/
theorem cramer (a b e q : Fin 3 → ℝ) :
    det3 a b e • q = det3 b e q • a + det3 e a q • b + det3 a b q • e := by
  funext i
  fin_cases i <;> simp [det3] <;> ring

theorem det3_comb_left (a b e : Fin 3 → ℝ) (l : Fin 3 → ℝ) :
    det3 b e (l 0 • a + l 1 • b + l 2 • e) = l 0 * det3 a b e := by
  simp only [det3, Pi.add_apply, Pi.smul_apply, smul_eq_mul]; ring

theorem det3_comb_mid (a b e : Fin 3 → ℝ) (l : Fin 3 → ℝ) :
    det3 e a (l 0 • a + l 1 • b + l 2 • e) = l 1 * det3 a b e := by
  simp only [det3, Pi.add_apply, Pi.smul_apply, smul_eq_mul]; ring

theorem det3_comb_right (a b e : Fin 3 → ℝ) (l : Fin 3 → ℝ) :
    det3 a b (l 0 • a + l 1 • b + l 2 • e) = l 2 * det3 a b e := by
  simp only [det3, Pi.add_apply, Pi.smul_apply, smul_eq_mul]; ring

/-- Three vectors with nonzero determinant give unique coefficients. -/
theorem coeffs_unique {a b e : Fin 3 → ℝ} (hD : det3 a b e ≠ 0) {l m : Fin 3 → ℝ}
    (h : l 0 • a + l 1 • b + l 2 • e = m 0 • a + m 1 • b + m 2 • e) : l = m := by
  have h0 := congrArg (det3 b e) h
  have h1 := congrArg (det3 e a) h
  have h2 := congrArg (det3 a b) h
  rw [det3_comb_left, det3_comb_left] at h0
  rw [det3_comb_mid, det3_comb_mid] at h1
  rw [det3_comb_right, det3_comb_right] at h2
  funext i
  fin_cases i
  · exact mul_right_cancel₀ hD h0
  · exact mul_right_cancel₀ hD h1
  · exact mul_right_cancel₀ hD h2

/-- If the three Cramer coefficients of `q` with respect to `a, b, e` are nonnegative and
`det3 a b e > 0`, then `q` is a nonnegative combination of `a, b, e`. -/
theorem cramer_coeffs {a b e q : Fin 3 → ℝ} (hD : 0 < det3 a b e) (h₁ : 0 ≤ det3 b e q)
    (h₂ : 0 ≤ det3 e a q) (h₃ : 0 ≤ det3 a b q) :
    ∃ l : Fin 3 → ℝ, (∀ i, 0 ≤ l i) ∧ q = l 0 • a + l 1 • b + l 2 • e := by
  set D := det3 a b e with hDdef
  refine ⟨![det3 b e q / D, det3 e a q / D, det3 a b q / D], ?_, ?_⟩
  · intro i
    fin_cases i
    · exact div_nonneg h₁ hD.le
    · exact div_nonneg h₂ hD.le
    · exact div_nonneg h₃ hD.le
  · have hc := cramer a b e q
    rw [← hDdef] at hc
    calc q = D⁻¹ • (D • q) := by rw [smul_smul, inv_mul_cancel₀ hD.ne', one_smul]
      _ = _ := by
        rw [hc]
        simp only [smul_add, smul_smul, Matrix.cons_val_zero, Matrix.cons_val_one,
          Matrix.cons_val_two, Matrix.tail_cons, Matrix.head_cons, div_eq_inv_mul]

/-! ### Cones -/

/-- The cone `{∑_{v ∈ S} μ_v v | μ ≥ 0}` generated by a finite set `S` of vectors. -/
def cone (S : Finset (Fin 3 → ℝ)) : Set (Fin 3 → ℝ) :=
  {q | ∃ μ : (Fin 3 → ℝ) → ℝ, (∀ v, 0 ≤ μ v) ∧ q = ∑ v ∈ S, μ v • v}

theorem zero_mem_cone (S : Finset (Fin 3 → ℝ)) : (0 : Fin 3 → ℝ) ∈ cone S :=
  ⟨fun _ => 0, fun _ => le_rfl, by simp⟩

theorem add_mem_cone {S : Finset (Fin 3 → ℝ)} {q₁ q₂ : Fin 3 → ℝ} (h₁ : q₁ ∈ cone S)
    (h₂ : q₂ ∈ cone S) : q₁ + q₂ ∈ cone S := by
  obtain ⟨μ₁, hμ₁, rfl⟩ := h₁
  obtain ⟨μ₂, hμ₂, rfl⟩ := h₂
  refine ⟨μ₁ + μ₂, fun v => add_nonneg (hμ₁ v) (hμ₂ v), ?_⟩
  simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]

theorem smul_mem_cone {S : Finset (Fin 3 → ℝ)} {q : Fin 3 → ℝ} {t : ℝ} (ht : 0 ≤ t)
    (h : q ∈ cone S) : t • q ∈ cone S := by
  obtain ⟨μ, hμ, rfl⟩ := h
  refine ⟨fun v => t * μ v, fun v => mul_nonneg ht (hμ v), ?_⟩
  simp only [Finset.smul_sum, mul_smul]

theorem mem_cone_of_mem {S : Finset (Fin 3 → ℝ)} {v : Fin 3 → ℝ} (hv : v ∈ S) : v ∈ cone S := by
  classical
  refine ⟨fun u => if u = v then 1 else 0, fun u => by by_cases h : u = v <;> simp [h], ?_⟩
  simp only [ite_smul, one_smul, zero_smul, Finset.sum_ite_eq', hv, ↓reduceIte]

theorem sum_mem_cone {S : Finset (Fin 3 → ℝ)} {ι : Type*} (s : Finset ι) (f : ι → Fin 3 → ℝ)
    (hf : ∀ i ∈ s, f i ∈ cone S) : ∑ i ∈ s, f i ∈ cone S := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using zero_mem_cone S
  | insert i s hi ih =>
    rw [Finset.sum_insert hi]
    exact add_mem_cone (hf i (Finset.mem_insert_self i s))
      (ih fun j hj => hf j (Finset.mem_insert_of_mem hj))

theorem cone_mono {S T : Finset (Fin 3 → ℝ)} (h : S ⊆ T) : cone S ⊆ cone T := by
  rintro q ⟨μ, hμ, rfl⟩
  exact sum_mem_cone S _ fun v hv => smul_mem_cone (hμ v) (mem_cone_of_mem (h hv))

theorem det3_nonneg_of_mem_cone {S : Finset (Fin 3 → ℝ)} {a b q : Fin 3 → ℝ}
    (hS : ∀ v ∈ S, 0 ≤ det3 a b v) (hq : q ∈ cone S) : 0 ≤ det3 a b q := by
  obtain ⟨μ, hμ, rfl⟩ := hq
  rw [det3_sum]
  exact Finset.sum_nonneg fun v hv => mul_nonneg (hμ v) (hS v hv)

theorem mem_cone_insert {S : Finset (Fin 3 → ℝ)} {x q : Fin 3 → ℝ} (hx : x ∉ S)
    (hq : q ∈ cone (insert x S)) : ∃ t : ℝ, 0 ≤ t ∧ ∃ r ∈ cone S, q = t • x + r := by
  obtain ⟨μ, hμ, rfl⟩ := hq
  rw [Finset.sum_insert hx]
  exact ⟨μ x, hμ x, _, ⟨μ, hμ, rfl⟩, rfl⟩

/-! ### Cutting off one ear -/

/-- Cutting off the ear `(p, x, s)` from a convex polygon with remaining vertex set `S`: the cone
of `insert x S` is covered by the cone of the triangle and the cone of `S`. The hypotheses say
that `det3 p x s > 0` and that every vertex of `S` lies weakly on the polygon side of the edges
`px` and `xs` and on the side of the diagonal `ps` away from `x`. -/
theorem ear_cover {S : Finset (Fin 3 → ℝ)} {p x s q : Fin 3 → ℝ} (hD : 0 < det3 p x s)
    (hpS : p ∈ S) (hsS : s ∈ S)
    (hS : ∀ y ∈ S, 0 ≤ det3 p x y ∧ 0 ≤ det3 x s y ∧ 0 ≤ det3 p s y)
    (hq : q ∈ cone (insert x S)) :
    (∃ l : Fin 3 → ℝ, (∀ i, 0 ≤ l i) ∧ q = l 0 • p + l 1 • x + l 2 • s) ∨ q ∈ cone S := by
  by_cases hx : x ∈ S
  · right
    rwa [Finset.insert_eq_of_mem hx] at hq
  have hS' : ∀ y ∈ insert x S, 0 ≤ det3 p x y ∧ 0 ≤ det3 x s y := by
    intro y hy
    rcases Finset.mem_insert.1 hy with rfl | hy
    · rw [det3_self_right, det3_self_left]; exact ⟨le_rfl, le_rfl⟩
    · exact ⟨(hS y hy).1, (hS y hy).2.1⟩
  have hpx : ∀ u ∈ cone (insert x S), 0 ≤ det3 p x u :=
    fun u hu => det3_nonneg_of_mem_cone (fun y hy => (hS' y hy).1) hu
  have hxs : ∀ u ∈ cone (insert x S), 0 ≤ det3 x s u :=
    fun u hu => det3_nonneg_of_mem_cone (fun y hy => (hS' y hy).2) hu
  have hlx : det3 p s x = -det3 p x s := by
    unfold det3; ring
  by_cases hl : det3 p s q ≤ 0
  · -- `q` lies on the side of the diagonal `ps` that contains `x`
    left
    refine cramer_coeffs hD (hxs q hq) ?_ (hpx q hq)
    rw [det3_swap]
    linarith
  · -- `q` lies on the other side of `ps`
    right
    replace hl := not_le.mp hl
    obtain ⟨t, ht, r, hr, rfl⟩ := mem_cone_insert hx hq
    have hrS : ∀ u ∈ cone S, u ∈ cone (insert x S) :=
      fun u hu => cone_mono (Finset.subset_insert x S) hu
    have hlr : 0 < det3 p s r := by
      rw [det3_add, det3_smul, hlx] at hl
      nlinarith
    have hlr' : 0 ≤ det3 p s r := hlr.le
    set θ := t * det3 p x s / det3 p s r with hθ
    have hθ0 : 0 ≤ θ := div_nonneg (mul_nonneg ht hD.le) hlr'
    have hθ1 : θ ≤ 1 := by
      rw [hθ, div_le_one hlr]
      rw [det3_add, det3_smul, hlx] at hl
      linarith
    set z := t • x + θ • r with hz
    have hzl : det3 p s z = 0 := by
      rw [hz, det3_add, det3_smul, det3_smul, hlx, hθ]
      field_simp
      ring
    have hzc : z ∈ cone (insert x S) :=
      add_mem_cone (smul_mem_cone ht (mem_cone_of_mem (Finset.mem_insert_self x S)))
        (smul_mem_cone hθ0 (hrS r hr))
    have hzS : z ∈ cone S := by
      obtain ⟨l, hl0, hl⟩ := cramer_coeffs hD (hxs z hzc)
        (by rw [det3_swap, hzl, neg_zero]) (hpx z hzc)
      have hl1 : l 1 = 0 := by
        have := det3_comb_mid p x s l
        rw [← hl, det3_swap, hzl, neg_zero] at this
        exact (mul_eq_zero.1 this.symm).resolve_right hD.ne'
      rw [hl, hl1, zero_smul, add_zero]
      exact add_mem_cone (smul_mem_cone (hl0 0) (mem_cone_of_mem hpS))
        (smul_mem_cone (hl0 2) (mem_cone_of_mem hsS))
    have hq' : t • x + r = z + (1 - θ) • r := by
      rw [hz, sub_smul, one_smul]; abel
    rw [hq']
    exact add_mem_cone hzS (smul_mem_cone (by linarith) hr)

/-! ### Convex position -/

/-- `CCW c`: every three entries of `c`, taken in list order, have positive determinant. As a
hypothesis it stands in for convex position in counterclockwise cyclic order (see the module
documentation). -/
def CCW (c : List (Fin 3 → ℝ)) : Prop :=
  ∀ a b e : Fin 3 → ℝ, [a, b, e].Sublist c → 0 < det3 a b e

theorem CCW.sublist {c d : List (Fin 3 → ℝ)} (hc : CCW c) (h : d.Sublist c) : CCW d :=
  fun a b e hs => hc a b e (hs.trans h)

theorem CCW.rotate_one {a : Fin 3 → ℝ} {l : List (Fin 3 → ℝ)} (h : CCW (a :: l)) :
    CCW (l ++ [a]) := by
  intro u v w hs
  rcases List.sublist_append_iff.1 hs with ⟨l₁, l₂, heq, h₁, h₂⟩
  rcases List.sublist_singleton.1 h₂ with rfl | rfl
  · rw [List.append_nil] at heq
    subst heq
    exact h u v w (h₁.trans (List.sublist_cons_self a l))
  · obtain ⟨rfl, rfl⟩ : l₁ = [u, v] ∧ w = a := by
      have := heq
      rw [show [u, v, w] = [u, v] ++ [w] from rfl] at this
      exact ⟨(List.append_inj' this rfl).1.symm, List.singleton_inj.1
        (List.append_inj' this rfl).2⟩
    rw [← det3_cycle]
    exact h w u v (List.Sublist.cons_cons w h₁)

theorem CCW.rotate {c : List (Fin 3 → ℝ)} (h : CCW c) (k : ℕ) : CCW (c.rotate k) := by
  induction k with
  | zero => simpa using h
  | succ k ih =>
    rw [← List.rotate_rotate]
    rcases hck : c.rotate k with _ | ⟨a, l⟩
    · simpa using ih.sublist (by rw [hck])
    · rw [hck] at ih
      rw [List.rotate_cons_succ, List.rotate_zero]
      exact ih.rotate_one

/-! ### Covering -/

/-- The triangles of an ear sequence of a `CCW` list cover the cone of its vertices: every vector
of that cone is a nonnegative combination of the three vertices of one triangle. -/
theorem IsEarSequence.cover {c : List (Fin 3 → ℝ)}
    {ts : List ((Fin 3 → ℝ) × (Fin 3 → ℝ) × (Fin 3 → ℝ))} (h : IsEarSequence c ts)
    (hc : CCW c) {q : Fin 3 → ℝ} (hq : q ∈ cone c.toFinset) :
    ∃ t ∈ ts, ∃ l : Fin 3 → ℝ, (∀ i, 0 ≤ l i) ∧ q = l 0 • t.1 + l 1 • t.2.1 + l 2 • t.2.2 := by
  classical
  induction h with
  | last a b e =>
    refine ⟨(a, b, e), List.mem_singleton_self _, ?_⟩
    have hD : 0 < det3 a b e := hc a b e (List.Sublist.refl _)
    have ha : 0 ≤ det3 b e a ∧ 0 ≤ det3 e a a ∧ 0 ≤ det3 a b a :=
      ⟨by rw [← det3_cycle a b e]; exact hD.le, (det3_self_right e a).ge, (det3_self_left a b).ge⟩
    have hb : 0 ≤ det3 b e b ∧ 0 ≤ det3 e a b ∧ 0 ≤ det3 a b b :=
      ⟨(det3_self_left b e).ge, by rw [det3_cycle e a b]; exact hD.le, (det3_self_right a b).ge⟩
    have he : 0 ≤ det3 b e e ∧ 0 ≤ det3 e a e ∧ 0 ≤ det3 a b e :=
      ⟨(det3_self_right b e).ge, (det3_self_left e a).ge, hD.le⟩
    have hS : ∀ v ∈ [a, b, e].toFinset, 0 ≤ det3 b e v ∧ 0 ≤ det3 e a v ∧ 0 ≤ det3 a b v := by
      intro v hv
      simp only [List.toFinset_cons, List.toFinset_nil, Finset.mem_insert,
        Finset.notMem_empty, or_false] at hv
      rcases hv with rfl | rfl | rfl
      exacts [ha, hb, he]
    exact cramer_coeffs hD (det3_nonneg_of_mem_cone (fun v hv => (hS v hv).1) hq)
      (det3_nonneg_of_mem_cone (fun v hv => (hS v hv).2.1) hq)
      (det3_nonneg_of_mem_cone (fun v hv => (hS v hv).2.2) hq)
  | ear c k p x s r ts hrot hr _ ih =>
    have hc' : CCW (p :: x :: s :: r) := hrot ▸ hc.rotate k
    have hD : 0 < det3 p x s := hc' p x s (by simp)
    have hfin : c.toFinset = insert x (p :: s :: r).toFinset := by
      have : c.toFinset = (c.rotate k).toFinset := by
        ext v; simp only [List.mem_toFinset, List.mem_rotate]
      rw [this, hrot]
      ext v
      simp only [List.toFinset_cons, Finset.mem_insert, List.mem_toFinset]
      tauto
    have hS : ∀ y ∈ (p :: s :: r).toFinset,
        0 ≤ det3 p x y ∧ 0 ≤ det3 x s y ∧ 0 ≤ det3 p s y := by
      intro y hy
      simp only [List.toFinset_cons, Finset.mem_insert, List.mem_toFinset] at hy
      rcases hy with rfl | rfl | hy
      · rw [det3_self_left, ← det3_cycle, det3_self_left]
        exact ⟨le_rfl, hD.le, le_rfl⟩
      · rw [det3_self_right, det3_self_right]
        exact ⟨hD.le, le_rfl, le_rfl⟩
      · have hy' : [y].Sublist r := List.singleton_sublist.2 hy
        refine ⟨(hc' p x y ?_).le, (hc' x s y ?_).le, (hc' p s y ?_).le⟩
        · exact List.Sublist.cons_cons p (List.Sublist.cons_cons x (hy'.cons s))
        · exact (List.Sublist.cons_cons x (List.Sublist.cons_cons s hy')).cons p
        · exact List.Sublist.cons_cons p ((List.Sublist.cons_cons s hy').cons x)
    rw [hfin] at hq
    rcases ear_cover hD (by simp) (by simp) hS hq with hl | hl
    · exact ⟨(p, x, s), List.mem_cons_self, hl⟩
    · have hnext : CCW (s :: (r ++ [p])) := by
        have h1 : CCW (p :: s :: r) :=
          hc'.sublist ((List.sublist_cons_self x (s :: r)).cons_cons p)
        exact h1.rotate_one
      have hfin' : (s :: (r ++ [p])).toFinset = (p :: s :: r).toFinset := by
        ext v
        simp only [List.toFinset_cons, List.toFinset_append, Finset.mem_insert,
          Finset.mem_union, List.mem_toFinset, List.toFinset_nil,
          Finset.mem_insert, Finset.notMem_empty, or_false]
        tauto
      rw [← hfin'] at hl
      obtain ⟨t, ht, hl'⟩ := ih hnext hl
      exact ⟨t, List.mem_cons_of_mem _ ht, hl'⟩

/-- Every triangle of an ear sequence of a `CCW` list has positive determinant. -/
theorem IsEarSequence.det_pos {c : List (Fin 3 → ℝ)}
    {ts : List ((Fin 3 → ℝ) × (Fin 3 → ℝ) × (Fin 3 → ℝ))}
    (h : IsEarSequence c ts) (hc : CCW c) : ∀ t ∈ ts, 0 < det3 t.1 t.2.1 t.2.2 := by
  induction h with
  | last a b e =>
    intro t ht
    rw [List.mem_singleton] at ht
    subst ht
    exact hc a b e (List.Sublist.refl _)
  | ear c k p x s r ts hrot hr _ ih =>
    have hc' : CCW (p :: x :: s :: r) := hrot ▸ hc.rotate k
    intro t ht
    rcases List.mem_cons.1 ht with rfl | ht
    · exact hc' _ _ _ (by simp)
    · refine ih ?_ t ht
      exact (hc'.sublist ((List.sublist_cons_self x (s :: r)).cons_cons p)).rotate_one

/-- `lem:frames` item 1 and `app:frames`, for one normal polygon in cone form. Let `c` be a list
of at least three vectors of `ℝ³` in which every three entries, in list order, have positive
determinant (`CCW c`, the stand-in for convex position in cyclic order). Then every vector `q`
of the cone generated by the entries of `c` lies in the cone of some triangle `(f₁, f₂, f₃)` of
the alternating-ear triangulation of `c`: there are coefficients `λ ≥ 0` with
`q = λ₁ f₁ + λ₂ f₂ + λ₃ f₃`, and no other coefficients (of any sign) represent `q` in that
triangle. -/
theorem exists_unique_coeffs_alternatingEars {c : List (Fin 3 → ℝ)} (hc3 : 3 ≤ c.length)
    (hc : CCW c) {q : Fin 3 → ℝ} (hq : q ∈ cone c.toFinset) :
    ∃ t ∈ alternatingEars c, ∃ l : Fin 3 → ℝ, (∀ i, 0 ≤ l i) ∧
      q = l 0 • t.1 + l 1 • t.2.1 + l 2 • t.2.2 ∧
      ∀ m : Fin 3 → ℝ, q = m 0 • t.1 + m 1 • t.2.1 + m 2 • t.2.2 → m = l := by
  have hseq := isEarSequence_alternatingEars hc3
  obtain ⟨t, ht, l, hl0, hl⟩ := hseq.cover hc hq
  refine ⟨t, ht, l, hl0, hl, fun m hm => ?_⟩
  exact coeffs_unique (hseq.det_pos hc t ht).ne' (hm.symm.trans hl)

/-! ### Clockwise order -/

/-- `CW c`: every three entries of `c`, taken in list order, have negative determinant. As a
hypothesis it stands in for convex position in clockwise cyclic order. -/
def CW (c : List (Fin 3 → ℝ)) : Prop :=
  ∀ a b e : Fin 3 → ℝ, [a, b, e].Sublist c → det3 a b e < 0

theorem det3_neg (a b e : Fin 3 → ℝ) : det3 (-a) (-b) (-e) = -det3 a b e := by
  simp only [det3, Pi.neg_apply]; ring

theorem CW.map_neg {c : List (Fin 3 → ℝ)} (h : CW c) : CCW (c.map Neg.neg) := by
  intro a b e hs
  have hs' : [-a, -b, -e].Sublist c := by
    simpa [List.map_map] using hs.map Neg.neg
  have := h _ _ _ hs'
  rw [det3_neg] at this
  linarith

theorem neg_mem_cone_map {c : List (Fin 3 → ℝ)} {q : Fin 3 → ℝ} (hq : q ∈ cone c.toFinset) :
    -q ∈ cone (c.map Neg.neg).toFinset := by
  obtain ⟨μ, hμ, rfl⟩ := hq
  refine ⟨fun u => μ (-u), fun u => hμ (-u), ?_⟩
  have hS : (c.map Neg.neg).toFinset = c.toFinset.image Neg.neg := by
    ext v; simp
  rw [hS, Finset.sum_image (fun x _ y _ h => neg_injective h)]
  simp only [neg_neg, smul_neg, Finset.sum_neg_distrib]

/-- The clockwise counterpart of `exists_unique_coeffs_alternatingEars`: the same conclusion
holds when every three entries of `c`, in list order, have negative determinant. -/
theorem exists_unique_coeffs_alternatingEars_of_cw {c : List (Fin 3 → ℝ)} (hc3 : 3 ≤ c.length)
    (hc : CW c) {q : Fin 3 → ℝ} (hq : q ∈ cone c.toFinset) :
    ∃ t ∈ alternatingEars c, ∃ l : Fin 3 → ℝ, (∀ i, 0 ≤ l i) ∧
      q = l 0 • t.1 + l 1 • t.2.1 + l 2 • t.2.2 ∧
      ∀ m : Fin 3 → ℝ, q = m 0 • t.1 + m 1 • t.2.1 + m 2 • t.2.2 → m = l := by
  obtain ⟨t, ht, l, hl0, hl, hu⟩ := exists_unique_coeffs_alternatingEars (c := c.map Neg.neg)
    (by simpa using hc3) hc.map_neg (neg_mem_cone_map hq)
  rw [alternatingEars_map, List.mem_map] at ht
  obtain ⟨t', ht', rfl⟩ := ht
  refine ⟨t', ht', l, hl0, ?_, fun m hm => hu m ?_⟩
  · rw [← neg_neg q, hl]
    simp only [smul_neg, neg_add, neg_neg]
  · rw [hm]
    simp only [smul_neg, neg_add]

/-- The covering statement of `exists_unique_coeffs_alternatingEars` for a normal polygon listed
in either cyclic orientation, that is, under `CCW c ∨ CW c`. -/
theorem exists_unique_coeffs_alternatingEars_of_convex {c : List (Fin 3 → ℝ)}
    (hc3 : 3 ≤ c.length) (hc : CCW c ∨ CW c) {q : Fin 3 → ℝ} (hq : q ∈ cone c.toFinset) :
    ∃ t ∈ alternatingEars c, ∃ l : Fin 3 → ℝ, (∀ i, 0 ≤ l i) ∧
      q = l 0 • t.1 + l 1 • t.2.1 + l 2 • t.2.2 ∧
      ∀ m : Fin 3 → ℝ, q = m 0 • t.1 + m 1 • t.2.1 + m 2 • t.2.2 → m = l :=
  hc.elim (fun h => exists_unique_coeffs_alternatingEars hc3 h hq)
    (fun h => exists_unique_coeffs_alternatingEars_of_cw hc3 h hq)

/-! ### Example -/

/-- A square in the plane `{u | u 2 = 1}`, listed counterclockwise, satisfies `CCW`. -/
example : CCW [![1, 0, 1], ![0, 1, 1], ![-1, 0, 1], ![0, -1, 1]] := by
  intro a b e h
  simp [List.sublist_cons_iff] at h
  rcases h with ⟨rfl, rfl, rfl⟩ | ⟨rfl, ⟨rfl, rfl⟩ | ⟨rfl, rfl | rfl⟩⟩ <;> norm_num [det3]

/-- The square listed in a non-cyclic order fails `CCW`. -/
example : ¬ CCW [![1, 0, 1], ![-1, 0, 1], ![0, 1, 1], ![0, -1, 1]] := by
  intro h
  have := h ![1, 0, 1] ![-1, 0, 1] ![0, 1, 1] (by simp)
  norm_num [det3] at this

end Triangulation

end Attention3D
